export const ADD_TODO = "ADD_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const COMPLETE_SELECTED_ITEM = "COMPLETE_SELECTED_ITEM";
export const DELETE_TODO = "DELETE_TODO";
export const DELETE_SELECTED_ITEM = "DELETE_SELECTED_ITEM";

export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";

