export const ADD_TODO = "ADD_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const COMPLETE_SELECTED_ITEM = "COMPLETE_SELECTED_ITEM";
export const DELETE_TODO = "DELETE_TODO";
export const DELETE_SELECTED_ITEM = "DELETE_SELECTED_ITEM";
export const CHECK_ITEM = "CHECK_ITEM";
export const CHECK_ALL_ITEM = "CHECK_ALL_ITEM";
export const EDIT_TODO = "EDIT_TODO";
export const SET_FILTER = "SET_FILTER";

