export const nameTask = '#task-tilte';
export const categoryTask = '#task-category';
export const dataTask = 'input[placeholder="Select date"]';
export const checkImportant = '#checkbox-important-task';
export const addToDoButton = '.ant-btn-block';
export const deleteButton = '.ant-table-tbody tr td:last-child a[href="#delete"]';
export const completeButton = '.ant-table-tbody tr td:last-child div';
export const okDelete ='.ant-popover .ant-btn-primary';
export const cancelDelete ='.ant-popover-buttons > :nth-child(1)';
export const pageDisplay ='.ant-pagination-options';